---
- name: Enable to install nginx.
  shell: "amazon-linux-extras enable nginx1"

- name: Install nginx
  yum:
    name: nginx
    state: latest

- name: Copy proxy.conf
  template:
    src: proxy.conf
    dest: /etc/nginx/conf.d/proxy.conf

- name: start nginx
  service:
    name: nginx
    state: restarted
    enabled: yes
