---
- name: restart firewalld.service
  systemd:
   name: firewalld.service
   state: restarted
   enabled: yes
   daemon_reload: yes

- name: restart chronyd.service
  systemd:
   name: chronyd.service
   state: restarted
   enabled: yes
   daemon_reload: yes

